In [1]:
import numpy as np

#defining a python list
myList=[1,2,3,4]

#converting the python list into numpy array
myArray=np.array(myList)

#print the array
print("myArray= ", myArray)


#arithmetic operations
myNewArray=myArray + 10
print("myNewArray= ", myNewArray)



myArray=  [1 2 3 4]
myNewArray=  [11 12 13 14]


In [2]:
#dimension of the array
#arrayname.ndim
print("Dimension: ", myArray.ndim)

#shape of the array
#arrayname.shape
print("Shape: ", myArray.shape)

#type of the array
#arrayname.dtype
print("Type: ",myArray.dtype)

#Element Size of the array
#arrayname.itemsize
print("Element Size: ", myArray.itemsize)

#array size 
#arrayname.size
print("Array Size  : ",myArray.size)


Dimension:  1
Shape:  (4,)
Type:  int32
Element Size:  4
Array Size  :  4


In [3]:
#2D array
twoArray = np.array([(1,2,3),
                    (4,5,6),
                    (7,8,9)])
print("2D Array : ",twoArray)
print("Dimension : ",twoArray.ndim)
print("2D Array Shape (rows,elements) : ", twoArray.shape)

#3D array
threeArray=np.array([
    [(1,2,3),(4,5,6)],
    [(1,2,3),(4,5,6)],
    [(1,2,3),(4,5,6)]
   
])
print("3D Array: ",threeArray)
print("Dimension : ",threeArray.ndim)
print("3D Array Shape (rows,columns,elements) : ",threeArray.shape)

2D Array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension :  2
2D Array Shape (rows,elements) :  (3, 3)
3D Array:  [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension :  3
3D Array Shape (rows,columns,elements) :  (3, 2, 3)


In [4]:
#Reshaping
# 1 2 3   ->  1 2
# 4 5 6   ->  3 4
#         ->  5 6

myArray=np.array([(1,2,3),(4,5,6)])
print(myArray)
print("My Array Shape:", myArray.shape)

#reshape(rows,elements)
reshapedArray=myArray.reshape(3,2)
print(reshapedArray)
print("Reshaped Array Shape: ",reshapedArray.shape)

[[1 2 3]
 [4 5 6]]
My Array Shape: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Reshaped Array Shape:  (3, 2)


In [5]:
#Slicing
#picking particular values

print(myArray)
#slicing third element from the first row
print(myArray[0,2])
#slicing third element from all the rows
print(myArray[0:,2])
#slicing first two elements from all the rows
print(myArray[0:,0:2])

[[1 2 3]
 [4 5 6]]
3
[3 6]
[[1 2]
 [4 5]]


In [6]:
#Spacing, Maximum, Minimum, Sum, Square Root, Standard Deviation

#linspace(start,end,no. of values)
myArray=np.linspace(1,2,10)
print(myArray)

#maximum
print("Maximum : ", myArray.max())
#minimum
print("Minimum : ", myArray.min())
#sum
print("Sum : ", myArray.sum())

#note the difference in the syntax of square root and standard deviation
#square root
print("Sqaure Root :  ",np.sqrt(myArray))
#standard deviation
print("Standard Deviation : ",np.std(myArray))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
Maximum :  2.0
Minimum :  1.0
Sum :  15.0
Sqaure Root :   [1.         1.05409255 1.1055416  1.15470054 1.20185043 1.24721913
 1.29099445 1.33333333 1.37436854 1.41421356]
Standard Deviation :  0.31914236925211265


In [7]:
#Axes
#Rows- Axis 1
#Columns - Axis 0

myArray=np.array([
    (1,2,3),
    (4,5,6)  
])
print("Sum across the Rows",myArray.sum(axis=0))
print("Sum across the Columns",myArray.sum(axis=1))
print("Minimum values across the columns",myArray.min(axis=1))
print("Minimum values across the rows",myArray.min(axis=0))

Sum across the Rows [5 7 9]
Sum across the Columns [ 6 15]
Minimum values across the columns [1 4]
Minimum values across the rows [1 2 3]


In [8]:
#Arithmetic Operations 
#result=a1+a2
#result=a1-a2
#result=a1*a2
#result=a1/a2

array1=np.array([(1,2,3),(4,5,6)])
array2=np.array([(7,8,9),(1,2,3)])
array3=array1+array2
print("Array 3 : ", array3)

Array 3 :  [[ 8 10 12]
 [ 5  7  9]]


In [9]:
#Vertical and Horizontal Stacking
#np.vstack((a1,a2,...))
#np.hstack((a1,a2,...))

array1=np.array([(1,2,3),(4,5,6)])
array2=np.array([(7,8,9),(10,11,12)])
array3=np.array([(1,1,1),(1,1,1)])
print(np.vstack((array1,array2,array3)))
print(np.hstack((array1,array2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  1  1]
 [ 1  1  1]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [10]:
#ravel
#converting multiline into a single line
#arrayname.ravel()

array1=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(array1.ravel())

[1 2 3 4 5 6 7 8 9]


In [11]:
#Special Functions

import matplotlib.pyplot as plt
x=np.arrange(0,3*pi,0.1)
y=np.sin(x)
plt.plot(x,y)
plt.show()

AttributeError: module 'numpy' has no attribute 'arrange'